---
collections:
  # Red Hat Supported Collections
  - name: ansible.posix
    source: https://console.redhat.com/api/automation-hub/
    version: 1.5.1
#  # Community Supported Collectiions
  - name: community.general
    source: https://galaxy.ansible.com/
    version: 6.5.0
